version: '3.8'

services:
  fantasynerds-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantasynerds-service
    ports:
      - "${APP_PORT:-8001}:8001"
    environment:
      - FLASK_APP=app.main:create_app
      - FANTASYNERDS_API_KEY=N6CBJDANYZPPTZHMWAVT
      - FANTASYNERDS_BASE_URL=https://api.fantasynerds.com
    command: python run.py
